keys:
  - &thinkpad age1naqzuryvv6xlkdzv398zd75znsv9u336etuukdqus6uwmk9m34aq4gawzp
  - &pi age1nuwxed3mq8ytz6vtaf2p7ax8mxldwyc5ee76mphxedfqpz3jnfuqfrey56
  - &desktop age1wyaw4my5d75fdvucq30ldc4s4a6ckaln02nwpeg2ddlpj0lmve9q8erj2j
  - &w2 age12dhwdqp8pgf30882mahnuppag5sfgp4wv9jagxsfl6glaawgppvss7800x

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
        - *thinkpad
        - *pi
        - *desktop
        - *w2