# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "ata_piix"
        "uhci_hcd"
        "virtio_pci"
        "virtio_scsi"
        "sd_mod"
        "sr_mod"
      ];
      systemd = {
        enable = true;
      };
      kernelModules = [ "btrfs" ];
    };

    kernel = {
      sysctl = {
        "net.ipv4.icmp_echo_ignore_broadcasts" = 1;
        "net.ipv6.conf.*.disable_ipv6" = 1;
        "fs.protected_hardlinks/symlinks" = 1;
        "fs.protected_fifos/regular" = 2;
        "net.core.default_qdisc" = "fq";
        "net.ipv4.tcp_cognestion_control" = "bbr";
      };
    };

    kernelModules = [
    ];
    extraModprobeConfig = "";
    extraModulePackages = [ ];
    kernelParams = [
      "ipv6.disable=1"
    ];
  };

  powerManagement = {
    cpuFreqGovernor = "performance";
  };

  networking = {
    useDHCP = lib.mkDefault true;
    # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  };

  nixpkgs = {
    hostPlatform = lib.mkDefault "x86_64-linux";
  };

}
