# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
      kernelModules = [ "lz4" ];
      systemd.enable = true;
    };

    kernel.sysctl = { 
      "vm.swappiness" = 10;
    };

    kernelModules = [ "kvm-amd" "v4l2loopback" ];
    extraModprobeConfig = ''options v4l2loopback exclusive_caps=1 card_label="Virtual Camera"'';
    extraModulePackages = [ ];
    kernelParams = [ "zswap.enabled=1" "zswap.compressor=lz4" "zswap.max_pool_percent=20" ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b50e11ea-b83f-4833-8eed-fb498f4da253";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/b50e11ea-b83f-4833-8eed-fb498f4da253";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/51B7-BC66";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  
  fileSystems."/mnt/storage" =
    { device = "/dev/disk/by-uuid/e46adfb8-aa7d-4d0a-99e4-41fc744b502f";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" ];
    };

  swapDevices = [ { 
     device = "/dev/nvme0n1p3";

  } ];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  # Automounts usb drives.
  services = {
    gvfs.enable = true;
    udisks2.enable = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  powerManagement.cpuFreqGovernor = "performance";
}
