# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    zfs = {
      forceImportRoot = false;
    };
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "zstd"
      ];
      kernelModules = [
        "lz4"
        "amdgpu"
      ];
    };

    kernelModules = [
      "r8169"
      "kvm-amd"
      "v4l2loopback"
    ];
    extraModprobeConfig = ''
      options v4l2loopback exclusive_caps=1 card_label="Virtual Camera"
    '';
    kernelParams = [
      "zswap.enabled=1"
      "zswap.compressor=lz4"
      "zswap.max_pool_percent=50"
      "r8169.disable_aspm=1"
      "r8169.disable_autosuspend=1"
    ];
  };

  hardware = {
    cpu = {
      amd = {
        updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };
    };
  };

  powerManagement = {
    cpuFreqGovernor = "performance";
  };

  services = {
    udev = {
      extraRules = ''
        	    ACTION=="add|change", SUBSYSTEM=="net", KERNEL=="enp34s0", RUN+="${pkgs.ethtool}/bin/ethtool -s $name wol g"
        	    ACTION=="add|change", SUBSYSTEM=="net", KERNEL=="enp34s0", RUN+="${pkgs.ethtool}/bin/ethtool --set-eee $name eee off"
        	    ACTION=="add|change", SUBSYSTEM=="net", KERNEL=="enp34s0", RUN+="${pkgs.bash}/bin/bash -c 'echo 1 > /sys/class/net/$name/device/power/wakeup'"
        	  '';
    };
  };

  nixpkgs = {
    hostPlatform = lib.mkDefault "x86_64-linux";
  };
}
