# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:

{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "usbhid"
        "xfs"
      ];
      kernelModules = [ ];
    };
    kernelParams = [
      "quiet"
      "loglevel=3"
      "rd.systemd.show_status_show"
      "rd_udev.log_level=3"
    ];
    kernelModules = [ ];
    extraModulePackages = [ ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5656-1F48";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7dc18054-7435-4ee8-9c6e-3ac55c5246c8";
    fsType = "xfs";
    options = [
      "noatime"
      "nodiratime"
    ];
  };

  networking = {
    useDHCP = lib.mkDefault true;
  };

  nixpkgs = {
    hostPlatform = lib.mkDefault "aarch64-linux";
  };

}
