# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "btrfs"
        "zstd"
      ];
      kernelModules = [
        "lz4"
        "amdgpu"
        "dm_crypt"
        "cryptd"
        "aesni_intel"
      ];
    };

    kernelModules = [
      "kvm-amd"
      "v4l2loopback"
    ];
    extraModprobeConfig = ''
      options v4l2loopback exclusive_caps=1 card_label="Virtual Camera"
      options iwlwifi power_save=0
      options iwlmvm power_scheme=1
      options cfg80211 ieee80211_regdom="TR"
    '';
    extraModulePackages = [ config.boot.kernelPackages.v4l2loopback ];
    kernelParams = [
      "zswap.enabled=1"
      "zswap.compressor=lz4"
      "zswap.max_pool_percent=20"
      "rd.luks.options=discard"
      "nvme.max_host_mem_size_mb=0"
      "nvme_core.default_ps_max_latency_us=5500"
    ];
  };

  hardware = {
    cpu = {
      amd = {
        updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      };
    };
    wirelessRegulatoryDatabase = true;
  };

  powerManagement = {
    cpuFreqGovernor = "powersave";
  };

  services = {
    fprintd = {
      enable = true;
      tod = {
        enable = true;
        driver = pkgs.libfprint-2-tod1-goodix-550a;
      };
    };
    fwupd = {
      enable = true;
    };
    udev = {
      extraRules = ''
        	    SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", TAG+="uaccess", ENV{MTP_NO_PROBE}="1", ENV{ID_MM_DEVICE_IGNORE}="1"
      '';
    };
  };

  nixpkgs = {
    hostPlatform = lib.mkDefault "x86_64-linux";
  };

}
