# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
        "btrfs"
      ];
      kernelModules = [ "lz4" ];
      systemd.enable = true;
    };

    kernel.sysctl = {
      "vm.swappiness" = 10;
      "net.ipv4.tcp_fin_timeout" = 30;
      "net.ipv4.tcp_max_syn_backlog" = 5000;
      "net.ipv4.tcp_rmem" = "4096 131072 12582912";
      "net.ipv4.tcp_wmem" = "4096 87380 4194304";
      "net.ipv4.tcp_congestion_control" = "bbr";
      "net.core.netdev_max_backlog" = 2000;
      "net.core.default_qdisc" = "fq";
      "net.core.rmem_max" = 2097152;
      "net.core.wmem_max" = 2097152;
      "net.ipv4.tcp_syncookies" = 1;
      "net.ipv4.icmp_echo_ignore_broadcasts" = 1;
      "net.ipv6.conf.*.disable_ipv6" = 1;
      "fs.protected_hardlinks/symlinks" = 1;
      "fs.protected_fifos/regular" = 2;
    };

    kernelModules = [
      "kvm-amd"
      "v4l2loopback"
    ];
    extraModprobeConfig = ''
      options v4l2loopback exclusive_caps=1 card_label="Virtual Camera"
      options iwlwifi power_save=0
      options iwlwifi bt_coex_active=0
    '';
    extraModulePackages = [ ];
    kernelParams = [
      "zswap.enabled=1"
      "zswap.compressor=lz4"
      "zswap.max_pool_percent=20"
      "ipv6.disable=1"
    ];
  };

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;

  # Automounts usb drives.
  services = {
    gvfs.enable = true;
    udisks2.enable = true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  powerManagement.cpuFreqGovernor = "performance";
}
